# Generated by Django 2.2 on 2019-05-28 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime(2019, 5, 28, 17, 31, 48, 606803)),
        ),
    ]
